# Generated by Django 4.1.1 on 2022-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmp_file", models.CharField(blank=True, max_length=150, null=True)),
                ("is_downloaded", models.BooleanField(default=False)),
                ("is_tg_uploaded", models.BooleanField(default=False)),
                ("is_compilation_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("coub_created_at", models.DateTimeField()),
            ],
        ),
    ]
