# Generated by Django 4.1.1 on 2022-10-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coub",
            name="coub_created_at",
        ),
    ]
