# Generated by Django 4.1.1 on 2022-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_compilation"),
    ]

    operations = [
        migrations.AddField(
            model_name="coub",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coub",
            name="h",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coub",
            name="w",
            field=models.IntegerField(default=0),
        ),
    ]
