# Generated by Django 4.1.1 on 2022-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_coub_duration_coub_h_coub_w"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="coub",
            name="tags",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
