# Generated by Django 4.0.5 on 2023-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tag_coub_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coub',
            name='is_good',
            field=models.BooleanField(default=True),
        ),
    ]
